-- MySQL Script generated by MySQL Workbench
-- Sat Jun  3 20:17:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `id_login` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `admin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rezervacija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rezervacija` (
  `id_rezervacija` INT NOT NULL AUTO_INCREMENT,
  `reservets` TINYINT(1) NOT NULL DEFAULT 0,
  `id_login` INT NOT NULL,
  PRIMARY KEY (`id_rezervacija`),
  INDEX `fk_rezervacija_login_idx` (`id_login` ASC) VISIBLE,
  CONSTRAINT `fk_rezervacija_login`
    FOREIGN KEY (`id_login`)
    REFERENCES `mydb`.`login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`papildu_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`papildu_info` (
  `idpapildu_info` INT NOT NULL,
  `nosaukums` VARCHAR(45) NOT NULL,
  `cena` DECIMAL(15,2) NOT NULL DEFAULT 5.00,
  PRIMARY KEY (`idpapildu_info`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media` (
  `id_media` VARCHAR(45) NOT NULL,
  `saite` VARCHAR(500) NULL,
  `media_tips` VARCHAR(45) NULL,
  PRIMARY KEY (`id_media`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`films` (
  `id_films` INT NOT NULL AUTO_INCREMENT,
  `zanrs` VARCHAR(50) NOT NULL,
  `vecums` VARCHAR(10) NOT NULL,
  `papildu_info_idpapildu_info` INT NOT NULL,
  `media_id_media` VARCHAR(45) NOT NULL,
  `filmscol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_films`),
  INDEX `fk_films_papildu_info1_idx` (`papildu_info_idpapildu_info` ASC) VISIBLE,
  INDEX `fk_films_media1_idx` (`media_id_media` ASC) VISIBLE,
  CONSTRAINT `fk_films_papildu_info1`
    FOREIGN KEY (`papildu_info_idpapildu_info`)
    REFERENCES `mydb`.`papildu_info` (`idpapildu_info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_films_media1`
    FOREIGN KEY (`media_id_media`)
    REFERENCES `mydb`.`media` (`id_media`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vietas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vietas` (
  `id_vieta` INT NOT NULL AUTO_INCREMENT,
  `vieta` INT NULL,
  `rinda` INT NULL,
  PRIMARY KEY (`id_vieta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bilete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bilete` (
  `id_bilete` INT NOT NULL AUTO_INCREMENT,
  `zale_numurs` INT NULL,
  `id_login` INT NOT NULL,
  `vietas_id_vieta` INT NOT NULL,
  `rezervacija_id_rezervacija` INT NOT NULL,
  `films_id_films` INT NOT NULL,
  PRIMARY KEY (`id_bilete`),
  INDEX `fk_bilete_vietas1_idx` (`vietas_id_vieta` ASC) VISIBLE,
  INDEX `fk_bilete_rezervacija1_idx` (`rezervacija_id_rezervacija` ASC) VISIBLE,
  INDEX `fk_bilete_films1_idx` (`films_id_films` ASC) VISIBLE,
  CONSTRAINT `fk_bilete_vietas1`
    FOREIGN KEY (`vietas_id_vieta`)
    REFERENCES `mydb`.`vietas` (`id_vieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bilete_rezervacija1`
    FOREIGN KEY (`rezervacija_id_rezervacija`)
    REFERENCES `mydb`.`rezervacija` (`id_rezervacija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bilete_films1`
    FOREIGN KEY (`films_id_films`)
    REFERENCES `mydb`.`films` (`id_films`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seansi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seansi` (
  `id_seansi` INT NOT NULL AUTO_INCREMENT,
  `datums` DATE NULL,
  `laiks` TIME NULL,
  `valoda` VARCHAR(45) NULL DEFAULT 'ENG',
  `subtitrus` BIT NULL DEFAULT 1,
  `films_id_films` INT NOT NULL,
  PRIMARY KEY (`id_seansi`),
  INDEX `fk_seansi_films1_idx` (`films_id_films` ASC) VISIBLE,
  CONSTRAINT `fk_seansi_films1`
    FOREIGN KEY (`films_id_films`)
    REFERENCES `mydb`.`films` (`id_films`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`login`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`login` (`id_login`, `username`, `password`, `admin`) VALUES (DEFAULT, 'nikita', 'Parole1', 0);
INSERT INTO `mydb`.`login` (`id_login`, `username`, `password`, `admin`) VALUES (DEFAULT, 'ruslans', 'Parole1', 0);
INSERT INTO `mydb`.`login` (`id_login`, `username`, `password`, `admin`) VALUES (DEFAULT, 'qwiza', 'Parole1', 0);
INSERT INTO `mydb`.`login` (`id_login`, `username`, `password`, `admin`) VALUES (DEFAULT, 'groshev', 'Parole1', 0);
INSERT INTO `mydb`.`login` (`id_login`, `username`, `password`, `admin`) VALUES (DEFAULT, 'admin', 'admin', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`rezervacija`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`rezervacija` (`id_rezervacija`, `reservets`, `id_login`) VALUES (DEFAULT, 0, DEFAULT);
INSERT INTO `mydb`.`rezervacija` (`id_rezervacija`, `reservets`, `id_login`) VALUES (DEFAULT, 0, DEFAULT);
INSERT INTO `mydb`.`rezervacija` (`id_rezervacija`, `reservets`, `id_login`) VALUES (DEFAULT, 0, DEFAULT);
INSERT INTO `mydb`.`rezervacija` (`id_rezervacija`, `reservets`, `id_login`) VALUES (DEFAULT, 0, DEFAULT);
INSERT INTO `mydb`.`rezervacija` (`id_rezervacija`, `reservets`, `id_login`) VALUES (DEFAULT, 0, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`papildu_info`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`papildu_info` (`idpapildu_info`, `nosaukums`, `cena`) VALUES (DEFAULT, 'Nežēlīgā nakts', DEFAULT);
INSERT INTO `mydb`.`papildu_info` (`idpapildu_info`, `nosaukums`, `cena`) VALUES (DEFAULT, 'Ziemassvētki džungļos', DEFAULT);
INSERT INTO `mydb`.`papildu_info` (`idpapildu_info`, `nosaukums`, `cena`) VALUES (DEFAULT, 'Avatars: Ūdensceļš', DEFAULT);
INSERT INTO `mydb`.`papildu_info` (`idpapildu_info`, `nosaukums`, `cena`) VALUES (DEFAULT, 'Circenīša Ziemassvētki', DEFAULT);
INSERT INTO `mydb`.`papildu_info` (`idpapildu_info`, `nosaukums`, `cena`) VALUES (DEFAULT, 'Lāčuka Tedija Ziemassvētki', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`media`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`media` (`id_media`, `saite`, `media_tips`) VALUES (DEFAULT, 'http://forumcinemaslv.blob.core.windows.net/1012/Event_9982/portrait_large/Violent-night-plakats.jpg', 'foto');
INSERT INTO `mydb`.`media` (`id_media`, `saite`, `media_tips`) VALUES (DEFAULT, 'http://forumcinemaslv.blob.core.windows.net/1012/Event_9468/portrait_large/Ziemassvetki-dzunglos-plakats.jpg', 'foto');
INSERT INTO `mydb`.`media` (`id_media`, `saite`, `media_tips`) VALUES (DEFAULT, 'https://www.bezrindas.lv/uploads/events/11300/ex2/daa434422410ed171460171a4c0a2bc3.png', 'foto');
INSERT INTO `mydb`.`media` (`id_media`, `saite`, `media_tips`) VALUES (DEFAULT, 'https://forumcinemaslv.blob.core.windows.net/1012/Event_9821/portrait_medium/Circenisa-Ziemassvetki-plakats.jpg', 'foto');
INSERT INTO `mydb`.`media` (`id_media`, `saite`, `media_tips`) VALUES (DEFAULT, 'https://www.bezrindas.lv/uploads/events/11177/e/66f4900e6a65cd037df6627dfb1f1459.jpg', 'foto');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`films`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`films` (`id_films`, `zanrs`, `vecums`, `papildu_info_idpapildu_info`, `media_id_media`, `filmscol`) VALUES (DEFAULT, 'Asa sižeta filma', '16+', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`films` (`id_films`, `zanrs`, `vecums`, `papildu_info_idpapildu_info`, `media_id_media`, `filmscol`) VALUES (DEFAULT, 'Ģimenes filma', '7+', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`films` (`id_films`, `zanrs`, `vecums`, `papildu_info_idpapildu_info`, `media_id_media`, `filmscol`) VALUES (DEFAULT, 'Piedzīvojumu filma', '12+', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`films` (`id_films`, `zanrs`, `vecums`, `papildu_info_idpapildu_info`, `media_id_media`, `filmscol`) VALUES (DEFAULT, 'Ģimenes filma', '7+', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`films` (`id_films`, `zanrs`, `vecums`, `papildu_info_idpapildu_info`, `media_id_media`, `filmscol`) VALUES (DEFAULT, 'Ģimenes filma', 'nav', DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`vietas`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`vietas` (`id_vieta`, `vieta`, `rinda`) VALUES (DEFAULT, 5, 3);
INSERT INTO `mydb`.`vietas` (`id_vieta`, `vieta`, `rinda`) VALUES (DEFAULT, 3, 8);
INSERT INTO `mydb`.`vietas` (`id_vieta`, `vieta`, `rinda`) VALUES (DEFAULT, 4, 6);
INSERT INTO `mydb`.`vietas` (`id_vieta`, `vieta`, `rinda`) VALUES (DEFAULT, 5, 8);
INSERT INTO `mydb`.`vietas` (`id_vieta`, `vieta`, `rinda`) VALUES (DEFAULT, 6, 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`bilete`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`bilete` (`id_bilete`, `zale_numurs`, `id_login`, `vietas_id_vieta`, `rezervacija_id_rezervacija`, `films_id_films`) VALUES (DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`bilete` (`id_bilete`, `zale_numurs`, `id_login`, `vietas_id_vieta`, `rezervacija_id_rezervacija`, `films_id_films`) VALUES (DEFAULT, 2, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`bilete` (`id_bilete`, `zale_numurs`, `id_login`, `vietas_id_vieta`, `rezervacija_id_rezervacija`, `films_id_films`) VALUES (DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`bilete` (`id_bilete`, `zale_numurs`, `id_login`, `vietas_id_vieta`, `rezervacija_id_rezervacija`, `films_id_films`) VALUES (DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`bilete` (`id_bilete`, `zale_numurs`, `id_login`, `vietas_id_vieta`, `rezervacija_id_rezervacija`, `films_id_films`) VALUES (DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;

